type: FeedbackConfig
## Шаблон сообщения, которое будет закрепляться и обновляться в канале.
template: |-
  Для предложения **фичи** или сообщения о **баге** используйте команду **/feedback**
  
  Для отправки на гитхаб вашей фичи необходимо собрать {min_feature_up_votes} или больше положительных реакции с вычетом отрицательных.
  За положительную реакцию считается {vote_up_emoji} а за отрицательную {vote_down_emoji}.

## Канал, в котором будут появляться сообщения от бота с предложением от пользователя с возможностью проголосовать.
#channel_id: 'channel_id'

## Реакция с таким эмодзи будет считаться как голос за.
#vote_up_emoji: '<:name:id>'

## Реакция с таким эмодзи будет считаться как голос против.
#vote_down_emoji: '<:name:id>'

## Количество голосов за для создания иссуя на гитхабе.
min_feature_up_votes: 25
