type: GithubConfig
## Токен для работы через API Github.
#token = 'token'

## Место, куда будут отправляться иссуи с предложениями. GitHub токен должен иметь доступ к нему.
#features_repository: 'owner/name'

## Место, куда будут отправляться иссуи с багами. GitHub токен должен иметь доступ к нему.
#bugs_repository: 'owner/name'
  
## Плашки, которые будут навешаны на иссуй с предложением.
feature_issue_labels:
  - ":robot:создано роботом"
  - "предложение"
  
## Плашки, которые будут навешаны на иссуй с багом.
bug_issue_labels:
  - ":robot:создано роботом"
  - "🐞 баг"