type: HttpConfig
## Адрес на котором будет работать сервер.
## Для доступности сервера извне используйте `0.0.0.0:<port>`
address: '127.0.0.1:4774'
## Перекомпиляция шаблонов при их изменений.
hot_reload: false