## Создаёт и постоянно обновляет сообщение со списком пользователей с ролью.
type: RolesListConfig
channels: []
## Канал, в котором будут сообщения.
#  - id: 'channel_id'
#    roles:
## Перечень ролей, по сообщению на каждую роль.
#      - id: 'role_id'
## Текст перед списком ролей.
#        title: 'Список администраторов:'
#        pin: true