## Все поля к заполнению обязательны (кроме url в loki).

[discord]
#guild_id = "guild_id"
#token = "token"

[github]
## Токен для работы через API GitHub.
#token = "token"

[commands.feedback]
## Шаблон сообщения, которое будет закрепляться и обновляться в канале.
template = """
Для предложения **фичи** или сообщения о **баге** используйте команду **/feedback**

Для отправки на гитхаб вашей фичи необходимо собрать {min_feature_up_votes} или больше положительных реакции с вычетом отрицательных.
За положительную реакцию считается {vote_up_emoji} а за отрицательную {vote_down_emoji}.
"""

## Канал, в котором будут появляться сообщения от бота с предложением от пользователя с возможностью проголосовать.
#channel_id = "channel_id"

## Место, куда будут отправляться иссуи с предложениями. GitHub токен должен иметь доступ к нему.
#features_repository = "owner/name"

## Место, куда будут отправляться иссуи с багами. GitHub токен должен иметь доступ к нему.
#bugs_repository = "owner/name"

## Реакция с таким эмодзи будет считаться как голос за.
#vote_up_emoji = "<:name:id>"

## Реакция с таким эмодзи будет считаться как голос против.
#vote_down_emoji = "<:name:id>"

## Количество голосов за для создания иссуя на гитхабе.
min_feature_up_votes = 25

## Плашки, которые будут навешаны на иссуй с предложением.
feature_issue_labels = [":robot:создано роботом", "предложение"]

## Плашки, которые будут навешаны на иссуй с багом.
bug_issue_labels = [":robot:создано роботом", "🐞 баг"]

[database]
## Не забудьте создать таблицу.
connect = "postgres://postgres:root@localhost/indigobot"

[logging]
## Уровень логирования.
log_level = "info"

[logging.loki]
enabled = false
## Уровень логирования для Локи.
log_level = "info"
## Место, куда отсылать логи при включённом Локи.
#url = "https://username:password@address"

[server]
## Адрес на котором будет работать сервер.
## Для доступности сервера извне используйте `0.0.0.0:<port>`
address = "127.0.0.1:8080"

[api]
## Особый секрет с полным доступом ко всему API, в БД он всегда имеет ID равным 1.
#root_secret = "secret"
