[logging]
## Уровень логирования.
log_level = "info"

[logging.loki]
enabled = false
## Уровень логирования для Локи.
log_level = "info"
## Место, куда отсылать логи при включённом Локи.
#url = "https://username:password@address"
