[package]
name = "app-macros"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.21"
syn = { version = "1.0.105", features = ["full"] }
proc-macro-crate = "1.2.1"
proc-macro2 = "1.0.47"
