[package]
name = "app-macros"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.23"
syn = { version = "1.0.107", features = ["full"] }
proc-macro-crate = "1.3.0"
proc-macro2 = "1.0.51"
