[package]
name = "app-discord-bot"
version = "1.0.0"
edition = "2021"

[dependencies]
app-shared = { path = "../app-shared" }
app-api = { path = "../app-api" }
app-macros = { path = "../app-macros" }

tracing = "0.1.37"
serde = { version = "1.0.152", features = ["derive"] }
